In [18]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [19]:
(X_train, y_train),(X_test,y_test)=keras.datasets.mnist.load_data()

In [20]:
X_train= X_train/255
X_test= X_test/255

In [21]:
X_train_flattened=X_train.reshape(len(X_train),28*28)
X_test_flattened=X_test.reshape(len(X_test),28*28)

In [22]:
X_train_flattened.shape

(60000, 784)

In [6]:
model= keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_flattened, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.4672 - accuracy: 0.8786
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3034 - accuracy: 0.9154
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2833 - accuracy: 0.9204
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2730 - accuracy: 0.9233
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2668 - accuracy: 0.9258


In [7]:
model.evaluate(X_test_flattened, y_test)

313/313 [==============================] - 2s 4ms/step - loss: 0.2667 - accuracy: 0.9271


[0.2667427957057953, 0.9271000027656555]

In [8]:
y_predicted= model.predict(X_test_flattened)
y_predicted[1]

313/313 [==============================] - 1s 3ms/step


array([5.8691847e-01, 3.8455457e-03, 9.9965179e-01, 3.5933432e-01,
       1.0456941e-09, 8.7010044e-01, 8.3440125e-01, 1.5415266e-12,
       1.9447654e-01, 4.1989110e-09], dtype=float32)

In [9]:
np.argmax(y_predicted[1])

2

In [10]:
y_predicted_labels=[np.argmax(i) for i in y_predicted]
y_predicted_labels[:5]

[7, 2, 1, 0, 4]

In [11]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [12]:
cm= tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 967,    0,    1,    2,    0,    4,    3,    2,    1,    0],
       [   0, 1111,    3,    2,    0,    1,    4,    2,   12,    0],
       [   6,    8,  929,   13,    9,    5,   10,   10,   39,    3],
       [   4,    0,   21,  914,    0,   28,    2,   11,   24,    6],
       [   2,    1,    6,    0,  933,    0,    5,    3,   10,   22],
       [  10,    2,    5,   26,   12,  782,   11,    5,   33,    6],
       [  12,    3,   10,    1,   10,   15,  901,    2,    4,    0],
       [   1,    5,   22,    6,   10,    0,    0,  950,    3,   31],
       [   8,    7,    6,   16,   10,   19,    7,   12,  881,    8],
       [  11,    7,    1,    9,   42,    7,    0,   23,    6,  903]])>

In [27]:
model= keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100,input_shape=(784,),activation='relu'),
    keras.layers.Dense(10,activation='sigmoid')
])

tb_callback= tf.keras.callbacks.TensorBoard(log_dir="logs/", histogram_freq=1)

model.compile(
    optimizer='SGD',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=5, callbacks=[tb_callback])

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.6438 - accuracy: 0.8377
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3345 - accuracy: 0.9064
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2859 - accuracy: 0.9194
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2567 - accuracy: 0.9273
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2345 - accuracy: 0.9342
